#version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    build: ../backend/
    env_file: ../.env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db
  nginx:
    container_name: foodgram-proxy
    # image: nginx:1.25.4-alpine
    build: ./
    env_file: ../.env
    ports:
      - '8000:80'
    volumes:
      - static:/staticfiles/
      - media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf


# services:
#   db:
#     image: postgres:13.10
#     env_file: ../.env
#     volumes:
#       - pg_data:/var/lib/postgresql/data
  # backend:
  #   build: ../backend/
  #   env_file: ../.env
  #   volumes:
  #     - static:/backend_static
  #     - media:/app/media/

  # frontend:
  #   container_name: foodgram-front
  #   build: ../frontend
  #   volumes:
  #     - ../frontend/:/app/result_build/
  # frontend:
  #   # env_file: ../.env
  #   container_name: foodgram-front
  #   build: ../frontend
  #   command: cp -r /app/build/. /frontend_static/
  #   volumes:
  #     # - static:/frontend_static
  #     # - media:/app/media/
  #     - ../frontend/:/app/result_build/
  # nginx:
  #   container_name: foodgram-proxy
  #   image: nginx:1.25.4-alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     # - static:/staticfiles/
  #     # - media:/app/media/
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/:/usr/share/nginx/html/api/docs/

