# Generated by Django 4.2.16 on 2024-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='загрузите аватар', upload_to='media/avatar', verbose_name='аватар'),
        ),
    ]
