# Generated by Django 4.2.16 on 2024-12-01 20:54

from django.db import migrations, models

import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_follow_author_alter_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[user.validators.validate_username], verbose_name='имя пользователя'),
        ),
    ]
