# Generated by Django 4.2.16 on 2024-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='загрузите аватар', upload_to='avatars/', verbose_name='аватар'),
        ),
    ]
