# Generated by Django 4.2.16 on 2024-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.URLField(help_text='Полная ссылка', max_length=150, unique=True, verbose_name='Полная ссылка')),
                ('short', models.CharField(default='x', help_text='Короткая ссылка', max_length=150, unique=True, verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ('id',),
                'default_related_name': 'link',
            },
        ),
    ]
