# Generated by Django 4.2.16 on 2024-11-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='full',
            field=models.CharField(help_text='Полная ссылка', max_length=150, unique=True, verbose_name='Полная ссылка'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short',
            field=models.CharField(default='x303', help_text='Короткая ссылка', max_length=150, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
