# Generated by Django 4.2.16 on 2024-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_alter_shortlink_full_alter_shortlink_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short',
            field=models.CharField(help_text='Короткая ссылка', max_length=150, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
