# Generated by Django 4.2.16 on 2024-12-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0003_alter_shortlink_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ('full',), 'verbose_name': 'ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
