# Generated by Django 4.2.16 on 2024-11-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Cостав', 'verbose_name_plural': 'Состав'},
        ),
    ]
