# Generated by Django 4.2.16 on 2024-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredientrecipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите фото блюда/рецепта', upload_to='recipes/', verbose_name='Фото блюда'),
        ),
    ]
